# Override values for flipenergy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 192.168.1.52

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
